// Package e2ee provides primitives for building End-to-End Encryption applications.
//
// This library follows the Signal Protocol's design patterns for key management
// and rotation, providing a simple and secure API for E2EE communications.
//
// It offers a high-level API for:
//   - Key Generation (Identity/Ed25519, Signed Prekeys/X25519)
//   - Prekey Bundles (X3DH-compatible for asynchronous key exchange)
//   - Prekey Rotation and Versioning (Signal Protocol pattern)
//   - Authenticated Encryption (Sign-then-Encrypt with XChaCha20-Poly1305)
//   - Digital Signatures (Ed25519)
//   - Key Lifecycle Management (expiration policies, pruning)
//
// This library aims to provide secure defaults and easy-to-use interfaces,
// avoiding common cryptographic pitfalls.
//
// Signal Protocol Compatibility:
//   - Identity Keys: Long-term Ed25519 keys (never rotated)
//   - Signed Prekeys: Medium-term X25519 keys (rotated periodically)
//   - Prekey Bundles: Standard format for key distribution
//
// For more information, see: https://signal.org/docs/specifications/x3dh/
//
// Disclaimer: This package was fully generated by an AI. It has not been
// audited by human security experts.
package e2ee
