// Package e2ee provides primitives for building End-to-End Encryption applications.
//
// It offers a high-level API for:
//   - Key Generation (Identity/Ed25519, Exchange/X25519)
//   - Authenticated Encryption (Sign-then-Encrypt with XChaCha20-Poly1305)
//   - Digital Signatures (Ed25519)
//
// This library aims to provide secure defaults and easy-to-use interfaces,
// avoiding common cryptographic pitfalls.
//
// Disclaimer: This package was fully generated by an AI. It has not been
// audited by human security experts.
package e2ee
